---
- name: Set user-defined variables
  hosts: localhost
  connection: local
  vars_prompt:
    - name: gitaly_benchmarking_deployment_name
      prompt: "Enter a name for your benchmark deployment"
      default: "{{ lookup('env', 'EXPERIMENT') }}-{{ lookup('env', 'USER') }}-{{ lookup('pipe', 'date +%Y%m%d') }}"
      private: false

    - name: gitaly_benchmarking_experiment_name
      prompt: "Enter the experiment to perform"
      default: "example"
      private: false

    - name: ssh_pubkey
      prompt: "Enter the path to your SSH public key"
      default: "{{ lookup('env', 'CI_SSH_PUBKEY_FILE') | default(lookup('env', 'HOME') ~ '/.ssh/id_ed25519.pub', true) }}"
      private: false
  roles:
    - deploy
  gather_facts: false
