---
- name: Load config
  include_vars:
    file: "{{ playbook_dir }}/config.yml"
    name: config

- name: Get current instance configuration
  set_fact:
    target_instance: "{{ config['gitaly_instances'] | selectattr('name', 'equalto', gitaly_name) | first }}"

- include_tasks: initialize.yml
- include_tasks: setup_go.yml
- include_tasks: setup_gitaly.yml
- include_tasks: setup_gitlab_shell.yml
- include_tasks: setup_profiling.yml
- include_tasks: setup_logging.yml
