---
- name: Install perf
  apt:
    name:
      - linux-tools-common
      - "linux-tools-{{ ansible_kernel }}"
      - "linux-headers-{{ ansible_kernel }}"
    state: present

- name: Install bpftrace
  ansible.builtin.get_url:
    url: https://github.com/bpftrace/bpftrace/releases/download/{{ bpftrace_version }}/bpftrace
    dest: /usr/local/bin/bpftrace
    mode: 0755

- name: Create /src directory
  file:
    path: /src
    state: directory
    mode: 0755

- name: Clone Flamegraph
  git:
    repo: https://github.com/brendangregg/flamegraph.git
    dest: /src/flamegraph
  become_user: git

- name: Install stackcollapse-perf.pl as stackcollapse
  copy:
    src: /src/flamegraph/stackcollapse-perf.pl
    dest: /usr/local/bin/stackcollapse
    mode: 0755
    remote_src: true

- name: Install flamegraph.pl as flamegraph
  copy:
    src: /src/flamegraph/flamegraph.pl
    dest: /usr/local/bin/flamegraph
    mode: 0755
    remote_src: true

- name: Install profile-gitaly.sh as profile-gitaly
  copy:
    src: profile-gitaly.sh
    dest: /usr/local/bin/profile-gitaly
    owner: root
    group: root
    mode: '0755'
