---
- name: Create benchmark results directory on Gitaly node
  file:
    path: "/tmp/{{ run_name }}"
    state: directory
    mode: "0755"
    owner: git
    group: git

- name: Create benchmark results directory on client node
  file:
    path: "/tmp/{{ run_name }}"
    state: directory
    mode: "0755"
    owner: git
    group: git
  delegate_to: "{{ groups['client'][0] }}"

# Clear the page cache so all runs start with a cold cache
- name: Clear kernel page cache
  shell: sync && echo 3 > /proc/sys/vm/drop_caches
  when: clear_page_cache | bool

# Create new Gitaly process for each run for easy log collection
- name: Start Gitaly service
  systemd:
    name: gitaly
    state: started
  notify: stop gitaly

- name: Pause for Gitaly to start up
  pause:
    seconds: 5

- name: Create benchmark-gitaly directory
  file:
    path: /opt/benchmark-gitaly
    state: directory
    mode: '0700'
    owner: git
    group: git
  delegate_to: "{{ groups['client'][0] }}"

- name: Copy workload configuration to client node
  copy:
    src: "{{ playbook_dir }}/k6-benchmark.js"
    dest: /opt/benchmark-gitaly/k6-benchmark.js
    mode: "0644"
    owner: git
    group: git
  delegate_to: "{{ groups['client'][0] }}"

# We run this task as async and poll 0 to make it non-blocking.
# It will be allowed to run up to `workload_wait_duration` before
# being treated as failed.
- name: Run k6
  command:
    argv:
      - k6
      - run
      - k6-benchmark.js
      - --summary-mode
      - full
      - --summary-export
      - /tmp/{{ run_name }}/k6-summary.json
      - --console-output
      - /tmp/{{ run_name }}/k6-console-logs.txt
    chdir: /opt/benchmark-gitaly
  environment:
    GITALY_ADDRESS: "{{ hostvars[groups['gitaly'][0]]['internal'] }}"
    GITALY_PROTO_DIR: "/src/gitaly/proto"
    RUN_NAME: "{{ run_name }}"
  async: "{{ workload_wait_duration }}"
  poll: 0
  register: workload_wait
  delegate_to: "{{ groups['client'][0] }}"

- name: Profile system with perf and libbpf-tools
  command:
    argv:
      - /usr/local/bin/profile-gitaly
      - "-d{{ profile_duration }}"
      - "-o/tmp/{{ run_name }}"
      - "-rbenchmark"
      - "-gbenchmark"
  when: profile | bool

- name: Wait for workload generator to exit
  async_status:
    jid: "{{ workload_wait.ansible_job_id }}"
  register: workload_result
  until: workload_result.finished
  retries: 100
  delay: 10
  delegate_to: "{{ groups['client'][0] }}"

- name: Copy workload data to Gitaly node
  synchronize:
    src: "/tmp/{{ run_name }}/"
    dest: "/tmp/{{ run_name }}/"
    private_key: /root/.ssh/id_ed25519
    set_remote_user: false
    recursive: true
  delegate_to: "{{ groups['client'][0] }}"

- name: Capture Gitaly logs
  shell: journalctl --output=cat _PID=$(pidof -s gitaly) > "/tmp/{{ run_name }}/gitaly.log"
