---
- name: GCloud login
  block:
    - name: GCloud login status
      command: gcloud auth application-default print-access-token
      changed_when: false
  rescue:
    - name: GCloud login
      command: gcloud auth application-default login

- name: terraform.tfvars
  template:
    src: terraform.tfvars.j2
    dest: "{{ playbook_dir }}/terraform/terraform.tfvars"

- name: terraform apply
  terraform:
    project_path: "{{ playbook_dir }}/terraform"
    variables_file: terraform.tfvars
    force_init: true
  register: tfstate
  notify:
    - add hostkeys

- name: hosts.ini
  template:
    src: hosts.ini.j2
    dest: "{{ playbook_dir }}/hosts.ini"

- name: Create group_vars directory
  file:
    path: "{{ playbook_dir }}/group_vars"
    state: directory

- name: Load config
  include_vars:
    file: "{{ playbook_dir }}/config.yml"
    name: config

- name: Get gitaly_revision
  set_fact:
    gitay_revision: "{{ config['gitaly_revision'] }}"

- name: all.yml
  template:
    src: all.yml.j2
    dest: "{{ playbook_dir }}/group_vars/all.yml"
